### ISSUE TITLE
The server REST API should allow the creation of data points

### ISSUE THREAD

**Issue by lhubert** [Hurence/historian#37]
It should be possible to add points through the REST API.. something like...
https://<historianserver>:XXX/historian-server   /v1/points/create
   {
   "TagName": "openSpaceSensors.Temperature",
   "points": [
                {
                   
                "TimeStamp": "2020-02-17T20:03:10.000Z",
                   
                "Value":   "25",
                   
                "Quality": 3
                }
           ]  
   }

**Comment by MiniPlayer** [comment]
I think a request like that would be allow to inject several type of metric at one time. And would optimize amount of data sent across network. We do not need to repeat "TimeStamp", "value" for every points. A long for the timestamp is also more efficient. Then latter we may accept others formats for convenience.
```
[
  {
    "name": "openSpaceSensors.Temperature",
    "points": [
      [1, 2.0],
      ...
      [6, 4.0]
    ]
  },
  ...
]
```
That's why I think Iwill go this way if nobody is against it.

**Comment by MiniPlayer** [comment]
Done partially with PR #93 . But the it creates a new chunk for every points and the chunks does not contain meta information like pre agregations.
